In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/prasad/Prasad Folder/DBDA/PML/cleaned_76hd.csv')
df

V3  V4        V9       V10       V11       V12       V14       V15  \
0    0.708333   1  0.000000  0.723618  0.003953  0.244292  0.505051  0.370370   
1    0.791667   1  0.023256  0.798995  0.003953  0.365297  0.404040  0.740741   
2    0.791667   1  0.023256  0.597990  0.003953  0.235160  0.202020  0.648148   
3    0.166667   1  0.015504  0.648241  0.000000  0.283105  0.000000  0.000000   
4    0.250000   0  0.007752  0.648241  0.003953  0.178082  0.000000  0.000000   
..        ...  ..       ...       ...       ...       ...       ...       ...   
277  0.208333   0  0.015504  0.688442  0.003953  0.214612  0.202020  0.425926   
278  0.583333   1  0.007752  0.768844  0.000000  0.242009  0.404040  0.648148   
279  0.604167   0  0.023256  0.648241  0.003953  0.162100  0.000000  0.000000   
280  0.583333   1  0.023256  0.547739  0.003953  0.477169  0.202020  0.277778   
281  0.375000   1  0.015504  0.648241  0.003953  0.289954  0.000000  0.000000   

     V16  V18  ...  V39       V40  V41       V43       V44   V51       V55  \
0      1    1  ...  0.0  0.370968  1.0  0.637037  0.000000  0.75  0.035714   
1      0    1  ...  0.0  0.241935  0.5  0.685185  1.000000  0.00  0.035714   
2      0    1  ...  0.0  0.419355  0.5  0.555556  0.666667  1.00  0.035714   
3      0    1  ...  0.0  0.564516  1.0  0.618519  0.000000  0.00  0.035714   
4      0    1  ...  0.0  0.225806  0.0  0.148148  0.000000  0.00  0.035714   
..   ...  ...  ...  ...       ...  ...       ...       ...   ...       ...   
277    0    0  ...  0.0  0.000000  0.5  0.596296  0.000000  0.00  0.142857   
278    0    1  ...  0.0  0.000000  0.0  0.229630  0.333333  0.00  0.178571   
279    0    1  ...  0.0  0.096774  0.5  0.348148  0.000000  0.00  0.071429   
280    0    1  ...  0.0  0.483871  0.5  0.337037  0.333333  1.00  0.142857   
281    0    1  ...  0.0  0.000000  0.0  0.203704  0.000000  0.00  0.142857   

          V56       V57  V58  
0    0.185185  0.964286    0  
1    0.049383  0.964286    1  
2    0.234568  0.964286    1  
3    0.037037  0.964286    0  
4    0.209877  0.964286    0  
..        ...       ...  ...  
277  0.098765  1.000000    0  
278  0.049383  1.000000    1  
279  0.345679  1.000000    0  
280  0.037037  1.000000    1  
281  0.283951  1.000000    0  

[282 rows x 39 columns]

In [3]:
X = df.drop("V58",axis=1)
Y = df['V58']

In [4]:
X.shape, Y.shape

((282, 38), (282,))

### **Train Test Split**

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train,Y_test = train_test_split(X,Y,
                                    test_size=0.3,
                                    random_state=7)

In [6]:
X_train.shape, X_test.shape, Y_train.shape,Y_test.shape

((197, 38), (85, 38), (197,), (85,))

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [8]:
lr = LogisticRegression(random_state = 7)
lr.fit(X_train, Y_train)
Y_pred_lr = lr.predict(X_test)

In [9]:
gb = GaussianNB()
gb.fit(X_train, Y_train)
Y_pred_gb = gb.predict(X_test)

In [10]:
sv = SVC(random_state = 7)
sv.fit(X_train, Y_train)
Y_pred_sv = sv.predict(X_test)

In [11]:
kn = KNeighborsClassifier()
kn.fit(X_train, Y_train)
Y_pred_kn = kn.predict(X_test)

In [22]:
dt = DecisionTreeClassifier(random_state=7)
dt.fit(X_train, Y_train)
Y_pred_dt = dt.predict(X_test)

In [13]:
Y_pred_lr 

array([0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [14]:
Y_pred_gb

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
Y_pred_sv

array([0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [16]:
Y_pred_kn 

array([0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1])

In [17]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred_lr))

              precision    recall  f1-score   support

           0       0.83      0.94      0.88        47
           1       0.91      0.76      0.83        38

    accuracy                           0.86        85
   macro avg       0.87      0.85      0.85        85
weighted avg       0.86      0.86      0.86        85



In [18]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred_gb))

              precision    recall  f1-score   support

           0       0.58      1.00      0.73        47
           1       1.00      0.11      0.19        38

    accuracy                           0.60        85
   macro avg       0.79      0.55      0.46        85
weighted avg       0.77      0.60      0.49        85



In [19]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred_sv))

              precision    recall  f1-score   support

           0       0.84      0.91      0.88        47
           1       0.88      0.79      0.83        38

    accuracy                           0.86        85
   macro avg       0.86      0.85      0.86        85
weighted avg       0.86      0.86      0.86        85



In [20]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred_kn))

              precision    recall  f1-score   support

           0       0.86      0.81      0.84        47
           1       0.78      0.84      0.81        38

    accuracy                           0.82        85
   macro avg       0.82      0.83      0.82        85
weighted avg       0.83      0.82      0.82        85



In [23]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred_dt))

              precision    recall  f1-score   support

           0       0.86      0.81      0.84        47
           1       0.78      0.84      0.81        38

    accuracy                           0.82        85
   macro avg       0.82      0.83      0.82        85
weighted avg       0.83      0.82      0.82        85



### Apply Ensemble Learning Models 

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rf = RandomForestClassifier(max_samples = 0.8, oob_score = True,
                       random_state=7)

In [27]:
rf.fit(X_train,Y_train)

RandomForestClassifier(max_samples=0.8, oob_score=True, random_state=7)

In [31]:
y_pred = rf.predict(X_test)

In [33]:
print(classification_report(Y_test,y_pred ))

              precision    recall  f1-score   support

           0       0.78      0.91      0.84        47
           1       0.87      0.68      0.76        38

    accuracy                           0.81        85
   macro avg       0.82      0.80      0.80        85
weighted avg       0.82      0.81      0.81        85



# XGBoost

In [36]:
import xgboost as xg

In [37]:
xgc = xg.XGBClassifier(random_state=7)

In [39]:
xgc.fit(X_train,Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [40]:
y_pred = xgc.predict(X_test)

In [42]:
from sklearn.metrics import f1_score


In [47]:
f1_score(Y_test,y_pred, average="micro" )

0.8117647058823529

In [49]:
print(classification_report(Y_test,y_pred ))

              precision    recall  f1-score   support

           0       0.82      0.85      0.83        47
           1       0.81      0.76      0.78        38

    accuracy                           0.81        85
   macro avg       0.81      0.81      0.81        85
weighted avg       0.81      0.81      0.81        85



In [51]:
xgc = xg.XGBClassifier(
                       learning_rate=0.1,
                       n_estimators=100,
                       max_depth=5,
                       subsample=0.8,
                       colsample_bytree=0.8,
                       random_state=7)
xgc.fit(X_train,Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [53]:

y_pred = xgc.predict(X_test)
print(classification_report(Y_test,y_pred ))

              precision    recall  f1-score   support

           0       0.79      0.89      0.84        47
           1       0.84      0.71      0.77        38

    accuracy                           0.81        85
   macro avg       0.82      0.80      0.81        85
weighted avg       0.82      0.81      0.81        85



# Catboost

In [54]:
import catboost

In [55]:
from catboost import CatBoostClassifier

In [56]:
cbc = CatBoostClassifier(random_state=7)

In [58]:
cbc.fit(X_train,Y_train)

Learning rate set to 0.005148
0:	learn: 0.6890584	total: 61ms	remaining: 1m
1:	learn: 0.6850906	total: 62.7ms	remaining: 31.3s
2:	learn: 0.6813316	total: 64.2ms	remaining: 21.4s
3:	learn: 0.6789906	total: 65.7ms	remaining: 16.4s
4:	learn: 0.6749706	total: 67.4ms	remaining: 13.4s
5:	learn: 0.6716541	total: 69.3ms	remaining: 11.5s
6:	learn: 0.6687615	total: 70.2ms	remaining: 9.96s
7:	learn: 0.6661795	total: 71.8ms	remaining: 8.91s
8:	learn: 0.6636259	total: 73.2ms	remaining: 8.06s
9:	learn: 0.6604272	total: 74.6ms	remaining: 7.38s
10:	learn: 0.6568288	total: 75.8ms	remaining: 6.82s
11:	learn: 0.6530038	total: 77.3ms	remaining: 6.36s
12:	learn: 0.6503136	total: 78.7ms	remaining: 5.97s
13:	learn: 0.6476165	total: 80.5ms	remaining: 5.67s
14:	learn: 0.6441056	total: 82ms	remaining: 5.39s
15:	learn: 0.6410472	total: 83.4ms	remaining: 5.13s
16:	learn: 0.6384454	total: 84.8ms	remaining: 4.91s
17:	learn: 0.6355275	total: 86.2ms	remaining: 4.71s
18:	learn: 0.6317765	total: 87.6ms	remaining: 4.52s

In [59]:
y_pred = cbc.predict(X_test)

In [60]:
f1_score(Y_test,y_pred, average="micro")

0.8235294117647058

In [62]:
print(classification_report(Y_test,y_pred ))

              precision    recall  f1-score   support

           0       0.82      0.87      0.85        47
           1       0.83      0.76      0.79        38

    accuracy                           0.82        85
   macro avg       0.82      0.82      0.82        85
weighted avg       0.82      0.82      0.82        85



In [63]:
cbc = CatBoostClassifier(iterations=100,
                         learning_rate=0.1,
                         depth=5,
                         cat_features=None,# list of names of categorical features
                         loss_function='MultiClass',#Logloss -> for binary classification
                         random_state=7)

In [65]:
cbc.fit(X_train,Y_train)

0:	learn: 0.6631182	total: 5.25ms	remaining: 520ms
1:	learn: 0.6427017	total: 7.08ms	remaining: 347ms
2:	learn: 0.6206216	total: 8.25ms	remaining: 267ms
3:	learn: 0.6033338	total: 9.14ms	remaining: 219ms
4:	learn: 0.5819910	total: 10ms	remaining: 191ms
5:	learn: 0.5623440	total: 10.9ms	remaining: 171ms
6:	learn: 0.5432820	total: 11.7ms	remaining: 155ms
7:	learn: 0.5233976	total: 12.9ms	remaining: 148ms
8:	learn: 0.5067337	total: 13.8ms	remaining: 140ms
9:	learn: 0.4926922	total: 14.7ms	remaining: 133ms
10:	learn: 0.4810125	total: 15.6ms	remaining: 126ms
11:	learn: 0.4712954	total: 16.4ms	remaining: 121ms
12:	learn: 0.4584947	total: 17.3ms	remaining: 116ms
13:	learn: 0.4474340	total: 18.2ms	remaining: 112ms
14:	learn: 0.4370423	total: 19ms	remaining: 108ms
15:	learn: 0.4232053	total: 19.8ms	remaining: 104ms
16:	learn: 0.4155361	total: 20.8ms	remaining: 101ms
17:	learn: 0.4090906	total: 21.5ms	remaining: 98.2ms
18:	learn: 0.4050848	total: 22.3ms	remaining: 95.2ms
19:	learn: 0.3962117	tot

# LightBGM

lgbm parameters

max_depth: int = -1,

learning_rate: float = 0.1,

n_estimators: int = 100

subsample

colsample_bytree (max_features)

random_state

In [68]:
pip install lightgbm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 855.5 kB/s eta 0:00:001m893.6 kB/s eta 0:00:01

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [70]:
# build the lightgbm model
import lightgbm as lgb
lgbm = lgb.LGBMClassifier()
lgbm.fit(X_train,Y_train)

[LightGBM] [Info] Number of positive: 90, number of negative: 107
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001278 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 578
[LightGBM] [Info] Number of data points in the train set: 197, number of used features: 35
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.456853 -> initscore=-0.173019
[LightGBM] [Info] Start training from score -0.173019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


LGBMClassifier()

In [71]:
y_pred = lgbm.predict(X_test)

In [73]:
f1_score(Y_test,y_pred, average="micro")

0.7764705882352941

In [75]:
print(classification_report(Y_test,y_pred ))

              precision    recall  f1-score   support

           0       0.77      0.85      0.81        47
           1       0.79      0.68      0.73        38

    accuracy                           0.78        85
   macro avg       0.78      0.77      0.77        85
weighted avg       0.78      0.78      0.77        85

