##### VD 23

# **NumPy**
- Numpy is Used for working with arrays.
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- Numpy is an incredible library to perform mathematical and statiscal operations due to it's fast and memory eficient as it is an optimized to work with latest CPU arichitectures.

In [1]:
import numpy as np

**NumPy arrays**

### **1)  0 Dimentional**

In [2]:

a = 45
print(a,"\nType of a is: ",type(a))


45 
Type of a is:  <class 'int'>


*Examples of 0D*

In [3]:
arr_o = np.array(a)
print(arr_o,"\nType of a is: ",type(arr_o))


45 
Type of a is:  <class 'numpy.ndarray'>


In [4]:
# To check the Dimention
print("As we know that this an example of:",arr_o.ndim)


As we know that this an example of: 0


In [5]:
# To check the shape 
print("The shape is:",arr_o.shape)

The shape is: ()


### **2)  1 Dimentional(1D)**

In [6]:
# Python list
a = [1,2,3,4]
print(a,type(a),"So this is a simple list")

[1, 2, 3, 4] <class 'list'> So this is a simple list


In [7]:
arr_1 = np.array(a)
print(arr_1, type(arr_1))


[1 2 3 4] <class 'numpy.ndarray'>


In [8]:
# Now to check wheather it is 1D or not we use following functions
arr_1.ndim

1

In [9]:
arr_1.shape

(4,)

#### **2.1)  Functions for Creating 1 Dimentional (1D) arrays**

**1) Arange Function**
   - Arange function is a array valued version of the build in Python range function.
   - **Syntax** - np.arange(start,end,step)

In [10]:
a = np.arange(1,10,2)

- Basically it gives values in range of 1 to 10 with step of 2 see the following output.

In [11]:
a

array([1, 3, 5, 7, 9])

**2) Linspace**
   - It returns evenly spaced numbers over a specified interval.
   - **Syntax** - np.linspace(start,end,num_of_samples)

In [12]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

- In the above example we are getting 6 samples evenly spaced

**3) Zeros**
   - It generates arrays of zeros.
   - **Syntax** - np.zeros(shape)

*Option 1*

In [13]:
np.zeros((4,))
# By default data type is Float

array([0., 0., 0., 0.])

*Option 2*

In [14]:
np.zeros((4,),dtype = int)

array([0, 0, 0, 0])

**4) Ones**
   - It generates arrays of ones.
   - **Syntax** - np.ones(shape)

*Option 1*

In [15]:
np.ones((4,))

array([1., 1., 1., 1.])

*Option 2*

In [16]:
np.ones((4,),dtype = int)

array([1, 1, 1, 1])

**4) random.randint**
   - Return random intergers from start to end 
   - **Syntax** - np.random.randint(start,end,num_of_samples)

In [17]:
np.random.randint(1,100,10)

array([96, 82, 48, 19, 45, 65, 87, 76, 14, 92])

#### **2.2) Accessing elements / Extracting values in  1 Dimentional (1D) arrays**

In [18]:
a = np.array([1,2,4,5,6,100,120 ,34,56,78])
a 

array([  1,   2,   4,   5,   6, 100, 120,  34,  56,  78])

**1) Accessing a single value through indexing**

Suppose we want to extract the element at index 2 we use following input

In [19]:
a[1]

2

**2) Accessing multiple value through slicing**

In [20]:
a[0:5:2]

array([1, 4, 6])

**3) Accessing multiple value through indexing**

syntax: arrayobj[[list of index numbers sep by comma]]

In [21]:
a[[1,2,5,6]]

array([  2,   4, 100, 120])

**4) Accessing multiple value Based on condition (Mask indexing or Fancy Indexing**

Syntax: arrayobj [condition]

In [22]:
a[a%2]

array([2, 1, 1, 2, 1, 1, 1, 1, 1, 1])

In [23]:
a[a>20]

array([100, 120,  34,  56,  78])

In [24]:
a[a==100]

array([100])

#### **2.3) Modify the values in  1 Dimentional (1D) arrays**

1) Add single value in array
2) Add multiple value in array
3) Replace a single value in array
4) Replace multiple values with a single in array
5) Replace multiple values with multiple values  in array
6) Delete multiple values in an array
7) Copy array
8) Sorting of array

**1) Add single value in array**

Syntax: np.append(arrayobj,value)

In [25]:
a = np.array([45,65,23,34,543,324])
a1 = np.append(a,110)
a1

array([ 45,  65,  23,  34, 543, 324, 110])

**2) Add multiple value in array**

Syntax: np.append(arrayobj,[values sep by comma])

In [27]:
a2 = np.append(a,[11,22,44,55,77,88])
a2

array([ 45,  65,  23,  34, 543, 324,  11,  22,  44,  55,  77,  88])

**3) Replace a single value in array**

In [28]:
a = np.array([45,65,23,34,543,324])
a[1] = 50000
a

array([   45, 50000,    23,    34,   543,   324])

**4) Replace multiple values with a single value in array**

In [ ]:
arrayobj[index numbers sep by comma] = value

In [29]:
a[[2,1]] = 0
a

array([ 45,   0,   0,  34, 543, 324])

**5) Replace multiple values with multiple values in array**

In [31]:
a5 = np.array([45,65,23,34,543,324])
a5 [[1,2]] = [10,20]
a5

array([ 45,  10,  20,  34, 543, 324])

**6) Delete multiple values in an array**

Syntax : np.delete(array,index number)

In [32]:
a = np.array([1,2,3,4])
np.delete(a,1)

array([1, 3, 4])

**7) Copy array**

Shallow Copy

In [33]:
a= np.array([23,34,65,67])
b = a.copy() 

In [34]:
print(a,id(a))
print(b,id(b))

[23 34 65 67] 4374312688
[23 34 65 67] 4374310768


Deep Copy

In [35]:
c = a
print(c,id(c))

[23 34 65 67] 4374312688


**7) Sorting an array**

In [36]:
a= np.array([23,34,65,67])
b = np.sort(a)
b

array([23, 34, 65, 67])

#### **2.4) Operations in  1 Dimentional (1D) arrays**

##### **2.4.1) Arithmetic Operations**

In [37]:
a = np.array([1,2,4,5,6])
b = a+1
b

array([2, 3, 5, 6, 7])

In [38]:
c = a**2
c

array([ 1,  4, 16, 25, 36])

In [39]:
(a+b)

array([ 3,  5,  9, 11, 13])

In [40]:
(a-b)

array([-1, -1, -1, -1, -1])

In [41]:
(a*b)

array([ 2,  6, 20, 30, 42])

##### **2.4.2) Comparision Operations**

In [42]:
a == b

array([False, False, False, False, False])

In [43]:
b>= a

array([ True,  True,  True,  True,  True])

In [44]:
np.array_equal(a,b)

False

##### **2.4.3) Mathematical Operations**

In [45]:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [46]:
import warnings
warnings.simplefilter("ignore")
np.log(a)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [47]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])