##### VD 24

### **2 Dimentional NumPy**

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
b = np.array([[0,1,2,5],[2,3,4,8]])
print(b)

[[0 1 2 5]
 [2 3 4 8]]


In [4]:
a.ndim

2

In [5]:
a.shape

(2, 3)

#### **1) Functions for Creating 2 Dimentional (2D) arrays**

**1) Zeros**


In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

We can also Perform Operations on this 

In [7]:
np.zeros((3,3),dtype = int) +1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Like that we are abe to set Datatype and along with it we can perform mathematical operation

**2) Ones**


In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

We can also Perform Operations on this same as zeros  

In [9]:
np.ones((3,3),dtype = int) +1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

**3) Identity Matrix**
- An identity matrix is a square matrix with ones on the diagonal and zeros elsewhere, acting as the multiplicative identity in matrix operations.


In [10]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**4) Diagonal Matrix**

In [11]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [12]:
a = np.array([[1,2,3],[3,4,5]])
np.diag(a)

array([1, 4])

#### **2) Accessing elements / Extracting values in  2 Dimentional (2D) arrays**

In [13]:
a = np.array([[10,20,30],[30,40,50],[20,80,90]])
a

array([[10, 20, 30],
       [30, 40, 50],
       [20, 80, 90]])

**1) To extract a single value from 2D array** 

- syntax: arrayobj[row index number , column index number]

In [14]:
a[1,2]

50

**2) To extract a single row**
- syntax: arrayobj[row index number]

In [15]:
a[2]

array([20, 80, 90])

**3) To extract multiple rows**
- syntax: arrayobj[start:end]

In [16]:
a[1:3]

array([[30, 40, 50],
       [20, 80, 90]])

#### **3) Modify the values in  2 Dimentional (2D) arrays**

**1)Replace a single value in 2D array**

In [17]:
a

array([[10, 20, 30],
       [30, 40, 50],
       [20, 80, 90]])

In [18]:
a[2,2]=7
a

array([[10, 20, 30],
       [30, 40, 50],
       [20, 80,  7]])

**2) Assigning value in 2D arrray**

In [19]:
a[1] = [23,30,60]
a

array([[10, 20, 30],
       [23, 30, 60],
       [20, 80,  7]])

**3) Flatening**

- Converting nd array to 1D

In [20]:
a = np.array([[0,1,2],[3,4,5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [21]:
b = a.ravel()
b

array([0, 1, 2, 3, 4, 5])

**4) Reshape array**

**Convert 1D Array to 2D**

In [22]:
arr = np.arange(6)

In [23]:
print(arr)

[0 1 2 3 4 5]


In [24]:
print(arr.shape)

(6,)


a1 = arr.reshape(6,1)
a1

In [25]:
a2 = arr.reshape(3,2)
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

**5) Transpose**

- Using this Function rows become columns and columns become rows

In [26]:
c = a.T
c

array([[0, 3],
       [1, 4],
       [2, 5]])

**6) Sorting**

- Sorting along an axis  ,
- axis =1 row and axis =0 column.

In [27]:
p = np.array([[8,5,6],[10,67,45]])
a = np.sort(p,axis = 0)
print(a)
b = np.sort(p,axis = 1)
b

[[ 8  5  6]
 [10 67 45]]


array([[ 5,  6,  8],
       [10, 45, 67]])

#### **4) Operations in  2 Dimentional (2D) arrays**

**1) Mathematical Operations**

In [28]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[40,4],[14,24],[34,54]])

- Addition

In [29]:
print(a+b)

[[41  6]
 [17 28]
 [39 60]]


- Multiplication

In [30]:
print(a*b)

[[ 40   8]
 [ 42  96]
 [170 324]]


- Matrix Multiplication

In [31]:
a = np.array([[1,2,1],[3,4,5],[5,6,5]])
b = np.array([[4,4,1],[4,4,2],[4,4,3]])
np.matmul(a,b)

array([[16, 16,  8],
       [48, 48, 26],
       [64, 64, 32]])

#### **5) Join Multiple  (2D) arrays**

In [32]:
a = np.array([[1,2,1],[3,4,5],[5,6,5]])
b = np.array([[4,4,1],[4,4,2],[4,4,3]])

In [33]:
np.concatenate((a,b),axis = 0)

array([[1, 2, 1],
       [3, 4, 5],
       [5, 6, 5],
       [4, 4, 1],
       [4, 4, 2],
       [4, 4, 3]])

**- Vertical stack**

In [34]:
a = np.array([[1,2,1],[3,4,5],[5,6,5]])
b = np.array([[4,4,1],[4,4,2],[4,4,3]])
np.vstack((a,b))

array([[1, 2, 1],
       [3, 4, 5],
       [5, 6, 5],
       [4, 4, 1],
       [4, 4, 2],
       [4, 4, 3]])

**- Horizontal stack**

In [35]:
a = np.array([[1,2,1],[3,4,5],[5,6,5]])
b = np.array([[4,4,1],[4,4,2],[4,4,3]])
np.hstack((a,b))

array([[1, 2, 1, 4, 4, 1],
       [3, 4, 5, 4, 4, 2],
       [5, 6, 5, 4, 4, 3]])